name: codspeed

on:
  push:
    branches:
      - main # Run on pushes to the main branch
  pull_request: # Run on all pull requests

jobs:
  codspeed:
    name: Run benchmarks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ x86_64 ]
        python-version: [ "3.12" ]
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: download test data
        run: just download-data

      - name: Rust latest
        run: rustup update

      - name: cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
          key: cargo-cache-${{ matrix.python-version }}-${{ matrix.target }}-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --all-extras --all-groups --no-install-project
        working-directory: ${{ github.workspace }}

      - name: maturin develop
        uses: PyO3/maturin-action@v1
        with:
          command: 'develop'
          args: --release
          sccache: 'true'
          manylinux: 'auto'
          working-directory: ${{ github.workspace }}
        env:
          # make sure profiling information is present
          CARGO_PROFILE_RELEASE_DEBUG: "line-tables-only"
          CARGO_PROFILE_RELEASE_STRIP: false

      - name: start services
        run: docker compose up --build --wait

      - uses: CodSpeedHQ/action@v3
        with:
          run: uv run --no-sync pytest --import-mode=importlib --codspeed
          token: ${{ secrets.CODSPEED_TOKEN }}
          working-directory: ${{ github.workspace }}
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DATABASE: ibis_testing